### ISSUE TITLE
Installation on debian10

### ISSUE THREAD

**Issue by JFsanchezherrero** [rsoftone/virmap#2]
Hi there,

I would like to test Virmap for processing some VirCapSeq data. I was wondering if the installation instructions you mention in this repository will work in debian 10 or what should I do to make it work.

Thanks

**Comment by IgnatiusPang** [comment]
Dear JFsanchezherrero,

I will just suggest you to give it a try and post any problems you've encountered here. I think there is a good chance that it will work, but perhaps with minor changes to the installation process. (It might just work as is, but I cannot guarantee.) Hopefully someone in the community will be able to response to the questions you might have.

Kind regards,

Igy
